services:
  cs-exp-go-api:
    build: .
    restart: always
    ports:
      - "8989:8989"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: your_jwt_secret_here
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql file

volumes:
  postgres_data: